[theme]
primaryColor = "#2F80ED"              # soft blue buttons and highlights
backgroundColor = "#FFFFF0"           # ivory background
secondaryBackgroundColor = "#F5F5F5"  # light gray sidebar
textColor = "#222222"                 # nearly black text
font = "sans serif"
